#define _AT_
#define _AT_ATE_
#define _AT_ATF_
#define _AT_CMEE_
#define _AT_FCLASS_
#define _AT_K_
#define _AT_SLED_
#define _AT_SLEDSAV_
#define _AT_E2SLRI_
//#define _AT_REGMODE_
//#define _AT_COPS_
#define _AT_AUTOBND_
#define _AT_SCFG_Out_
#define _AT_SCFGEXT_Out_
#define _AT_SCFG_In_
#define _AT_SCFGEXT_In_
#define _AT_TXMONMODE_
#define _AT_CREG_
#define _AT_CGREG_
#define _AT_CCLK_
#define _AT_CGDCONT_
#define _AT_SGACT_
#define _AT_ICMP_
#define _AT_CPIN_
#define _AT_CGSN_
#define _AT_GSN_
#define _AT_GMI_
#define _AT_GMM_
#define _AT_GMR_
#define _AT_ICCID_
//#define _AT_SERVINFO_
#define _AT_MONIZIP_
//#define _AT_CSQ_