// Library Commands
#define _AT_FULL_
// #define _AT_LITE_

// Define Full AT Command Index
#ifdef _AT_FULL_
    #define _AT_
    #define _AT_ATE_
    #define _AT_CMEE_
    #define _AT_FCLASS_
    #define _AT_K_
    #define _AT_CPIN_
    #define _AT_QSS_
    #define _AT_CGSN_
    #define _AT_GSN_
    #define _AT_CCID_
    #define _AT_GMI_
    #define _AT_GMM_
    #define _AT_GMR_
    #define _AT_SLED_
    #define _AT_E2SLRI_
    #define _AT_E2RI_
    #define _AT_REGMODE_
    #define _AT_TXMONMODE_
    #define _AT_AUTOBND_
    #define _AT_COPS_
    #define _AT_CREG_
    #define _AT_CGREG_
    #define _AT_CGDCONT_
    #define _AT_SGACT_
    #define _AT_CGACT_
    #define _AT_CGPADDR_
    #define _AT_ICMP_
    #define _AT_CSQ_
    #define _AT_SERVINFO_
    #define _AT_MONI_
    #define _AT_MONIZIP_
    #define _AT_CTZU_
    #define _AT_NITZ_
    #define _AT_NTP_
    #define _AT_CCLK_
    #define _AT_FRWL_
    #define _AT_HTTPCFG_
    #define _AT_HTTPSND_
    #define _AT_HTTPRCV_
    #define _AT_SCFG_
    #define _AT_SCFGEXT_
    #define _AT_SCFGEXT2_
    #define _AT_SCFGEXT3_
    #define _AT_SS_
    #define _AT_SL_
    #define _AT_SH_
    #define _AT_SO_
    #define _AT_SA_
    #define _AT_SD_
    #define _AT_SSEND_
    #define _AT_SRECV_
    #define _AT_SHDN_
#endif

// Define Lite AT Command Index
#ifdef _AT_LITE_
    #define _AT_
    #define _AT_ATE_
    #define _AT_CMEE_
    #define _AT_FCLASS_
    #define _AT_K_
    #define _AT_CPIN_
    #define _AT_QSS_
    #define _AT_CGSN_
    #define _AT_GSN_
    #define _AT_CCID_
    #define _AT_GMI_
    #define _AT_GMM_
    #define _AT_GMR_
    #define _AT_SLED_
    #define _AT_E2SLRI_
    #define _AT_E2RI_
    #define _AT_REGMODE_
    #define _AT_TXMONMODE_
    #define _AT_AUTOBND_
    #define _AT_COPS_
    #define _AT_CREG_
    #define _AT_CGREG_
    #define _AT_CGDCONT_
    #define _AT_SGACT_
    #define _AT_CGACT_
    #define _AT_CGPADDR_
    #define _AT_ICMP_
    #define _AT_CSQ_
    #define _AT_SERVINFO_
    #define _AT_MONI_
    #define _AT_MONIZIP_
    #define _AT_CTZU_
    #define _AT_NITZ_
    #define _AT_NTP_
    #define _AT_CCLK_
    #define _AT_FRWL_
    #define _AT_HTTPCFG_
    #define _AT_HTTPSND_
    #define _AT_HTTPRCV_
    #define _AT_SCFG_
    #define _AT_SCFGEXT_
    #define _AT_SCFGEXT2_
    #define _AT_SCFGEXT3_
    #define _AT_SS_
    #define _AT_SL_
    #define _AT_SH_
    #define _AT_SO_
    #define _AT_SA_
    #define _AT_SD_
    #define _AT_SSEND_
    #define _AT_SRECV_
    #define _AT_SHDN_
#endif